import os

class Config:
    SECRET_KEY = os.environ.get('FINDATEACHER_SECRET_KEY')
    SQLALCHEMY_DATABASE_URI = os.environ.get('FINDATEACHER_SQLALCHEMY_DATABASE_URI')
    GOOGLE_MAPS_API_KEY = os.environ.get('FINDATEACHER_GOOGLE_MAPS_API_KEY')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_ECHO = True